### ISSUE TITLE
make decoder run only on the respective cookie (and not all cookies)

### ISSUE THREAD

**Issue by schlichtanders** [dqunbp/use-cookie-state#3]
Using this code for 15 minutes I realized that the cookies parsing functionality and all its respective utility as decode and encode tools will always be run for all cookies.

It would make much more sense to the user if the decode function would only be run for the very cookie which is identified by name.

**Comment by dqunbp** [comment]
@schlichtanders The downside of this approach is that you won't be able to apply the `decode` function to a raw value from a cookies; By default, `cookie` lib will apply `decodeUriComponent` will for each value, and then `decode` will be applied to the target value.

**Comment by dqunbp** [comment]
@schlichtanders In release 3.0.0, this works as you requested, but starting from 3.1.0, I reverted it to the previous behavior. The fact that it runs for the all values from the cookies is a small price to pay for the ability to fully control encoding and decoding. Otherwise, it would be impossible to prevent `decodeURIComponent` from being called before custom `decode` function. Alternatively, I would have to implement the parsing yourself without using cookie lib, which goes against the original intent of this hook—to leverage the cookies library under the hood, as it is already a proven and popular solution.

**Comment by schlichtanders** [comment]
thank you for your effort and all your thoughts. makes sense
